### ISSUE TITLE
Implement persistent subscriptions

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore-Client-Go#16] opened 2020-08-31 13:16 UTC
- [ ] Create/Update/Delete
- [ ] Subscribing

**Comment by radovanEmbroker** [comment] 2021-06-16 08:49
Hi @hayley-jean,  
I have started to work on this as a side project of mine. Got to the point where I need to write integration tests to check if everything works as intended. 
I want to use gRPC test data docker image for integration tests. I am able to login using my github token. Token has repo and write:packages scopes.
I cannot fetch docker images with command:
```
docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:20.6.1-buster-slim
```
I get error:
```
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```

I tried to fetch other docker images and I got the same error.

**Comment by pivonroll** [comment] 2021-06-16 08:51
Hi @hayley-jean,
I have started to work on this as a side project of mine. Got to the point where I need to write integration tests to check if everything works as intended.
I want to use gRPC test data docker image for integration tests. I am able to login using my github token. Token has repo and write:packages scopes.
I cannot fetch docker images with command:
```
docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:20.6.1-buster-slim
```
I get error:
```
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```
I tried to fetch other docker images and I got the same error.

**Comment by pivonroll** [comment] 2021-06-16 09:05
Link to the pull request https://github.com/EventStore/EventStore-Client-Go/pull/51

**Comment by hayley-jean** [comment] 2021-06-17 09:54
Hi @pivonroll, thanks for the PR!

From what you describe, the token you're using should work for fetching that docker image and it's working on my side as well. Could you double check your login and make sure everything's correct?

You could also try and pull one of the other docker containers to see if it's just an issue with the test data container. For example, the [EventStore ci container](https://github.com/EventStore/EventStore/packages/68255).

Otherwise you could build the test data container locally and test against that, you can find it here: https://github.com/EventStore/EventStore-Client-gRPC-TestData

**Comment by pivonroll** [comment] 2021-06-21 16:29
You are welcome!
Sorry for the late response, I was busy cleaning up the code and adding unit tests to the persistent subscription client.

I really tried to pull the image in question but without any luck.
I managed to build my own test data container by using the image from docker hub. I wasn't hard. Pretty easy ;)
I will update the Readme with the info on how to build you own docker image by using the one from docker hub as a base.

At the moment I am not able to login at https://docker.pkg.github.com, probably it's ongoing issue which will be resolved by Github staff. I will try to pull the docker image from the link you sent me, once the issue with login is resolved.

I just need to add a few tests to the PR.
I didn't wanted to provide the async read client for persistent messages **at the moment** because developers like to implement async operations in accord to their own needs and I didn't wanted to prolong this PR by extending it's scope with async read support.
Still, I do have an idea how to do it with channels, but I want to provide tests as well, because I do not want to post the code for which I cannot guarantee (at least to some degree) that it works as intended.

I have two suggestions for future PRs:
1. This client would benefit from a small code cleanup and decoupling, especially on the relation client <-> stream subscription (not persistent one). If this is pulled under the rug the client's features and scalability suffer in near future.
2. Client code should be formatted by using either https://github.com/mvdan/gofumpt or gofmt formatters as it would be easier to read the code. Some code lines go for 200 or more characters which is hard to read on laptops with FullHD resolution.

**Comment by pivonroll** [comment] 2021-06-22 10:10
I am able to login with:
```
cat ~/<my token file> | docker login docker.pkg.github.com -u <my user name> --password-stdin
```

I tried to pull:
```
docker pull docker.pkg.github.com/eventstore/eventstore/eventstore:21.6.1-alpha.0.2-buster-slim
```
and 
```
docker pull docker.pkg.github.com/eventstore/eventstore/eventstore:21.6.0-focal
```

Both pulls returned the same error:
```
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```

**Comment by YoEight** [comment] 2021-09-07 17:30
Done

**Closed by YoEight** 2021-09-07 17:30 UTC
