### ISSUE TITLE
Apply Deadlines RFC

### ISSUE THREAD

**Issue by YoEight** [EventStore/EventStore-Client-Go#90] opened 2022-01-24 12:42 UTC
Reference: https://github.com/EventStore/architecture-and-planning/blob/main/rfcs/032%20-%20grpc-clients-deadlines.md

**Comment by hayley-jean** [comment] 2022-02-15 09:27
Closing as duplicate of https://github.com/EventStore/EventStore-Client-Go/issues/92

**Closed by hayley-jean** 2022-02-15 09:27 UTC
Labels: tier/minimum-viable
